BASE  <https://elections.ontotext.com/resource/>
PREFIX myp: <https://elections.ontotext.com/resource/prop/indirect/>
PREFIX myd: <https://elections.ontotext.com/resource/prop/direct/>
PREFIX election: <https://elections.ontotext.com/resource/election/>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX myc: <https://elections.ontotext.com/resource/prop/cube/>
PREFIX myps: <https://elections.ontotext.com/resource/prop/statement/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX mypq: <https://elections.ontotext.com/resource/prop/qualifier/>
CLEAR SILENT GRAPH <graph/cube/sofia-profiling/bsp> ;
INSERT {
  graph <graph/cube/sofia-profiling/bsp> {
  ?VOTES_URI a qb:Observation , myc:Voting ;
             qb:dataSet <cube/sofia-profiling> ;
             myc:locality ?locality ;
             myc:candidate ?candidate ;
             myc:votes ?VOTES ;
   .
  }
} where {
   bind("bsp" as ?candidate)
   ?voting myp:vote ?vote ;
              myd:voters_count ?voters_count ;
              myd:voters_voted_count ?voted_count ;
              myd:main_election election:pi2023 ;
          	  myd:section ?locality ;
    .
    ?locality myd:place/myd:municipality jurisdiction:2246 .

    ?vote myps:vote/myd:party/myd:party wd:Q752259;
              mypq:valid_votes_recieved ?VOTES ;
      bind(uri(concat("cube/votes/",str(sha1(concat(str(?locality),str(?candidate),str(election:pi2023)))))) as ?VOTES_URI)
}