PREFIX my: <https://elections.ontotext.com/resource/entity/>
PREFIX myd: <https://elections.ontotext.com/resource/prop/direct/>
PREFIX election: <https://elections.ontotext.com/resource/election/>
PREFIX risky_model: <https://elections.ontotext.com/resource/risky_model/>
PREFIX myp: <https://elections.ontotext.com/resource/prop/indirect/>
PREFIX mypq: <https://elections.ontotext.com/resource/prop/qualifier/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX myps: <https://elections.ontotext.com/resource/prop/statement/>
select ?election ?total_voted ?total_risky ?party_name ?party_num ?party_voted
(sum(?party_risky) as ?party_risky)
(?party_risky/?party_voted as ?party_ratio_in_risky_sections)
(?party_risky/?total_risky as ?risky_ratio_by_party)
{
    {
        select ?election ?total_voted ?party ?total_risky
        (sum(?party_votes) as ?party_voted)
        {
            {
                select ?election ?total_voted (sum(?voted_risky) as ?total_risky){
                    {
                        select
                        ?election
                        (sum(?voted) as ?total_voted)
                        where {
                            bind(election:pi2021_11 as ?election)
                            ?v a my:Voting ;
                               myd:main_election ?election;
                               myd:voters_voted_count ?voted ;
                               .
                        } group by ?election
                    }
                    ?v a my:Voting ;
                       myd:section ?sec ;
                       myd:voters_voted_count ?voted_risky ;
                       myd:main_election ?election ;
                       .
                    ?sec myd:matched_section/myd:risk_model risky_model:akf_all_time_risky .
                } group by ?election ?total_voted
            }
            ?v a my:Voting ;
               myd:section ?sec ;
               myd:main_election ?election ;
               myp:vote ?vs ;
               .
            ?vs mypq:result_order ?order ;
                mypq:valid_votes_recieved ?party_votes ;
                myps:vote/myd:party ?party ;
                         .
        } group by ?election ?total_voted ?all_sections ?party ?total_risky
    }
    ?v a my:Voting ;
       myd:section ?sec ;
       myd:main_election ?election ;
       myp:vote ?vs ;
       .
    ?vs mypq:result_order ?order ;
        mypq:valid_votes_recieved ?party_risky ;
        myps:vote/myd:party ?party ;
                 .
    ?party rdfs:label ?party_name ;
           myd:number ?party_num .
    ?sec myd:matched_section/myd:risk_model risky_model:akf_all_time_risky .
} group by ?election ?total_voted ?total_risky ?party_name ?party_num ?party_voted order by desc(?party_voted)